[[extensions]]
name = "stock-automation"
type = "flow_trigger"
handle = "stock-automation"
description = "Your description"

[settings]

  [[settings.fields]]
  type = "customer_reference"

  [[settings.fields]]
  type = "single_line_text_field"
  key = "Your field key"
